### ISSUE TITLE
Are the values properly converted to ppm

### ISSUE THREAD

**Issue by derekgair** [wifwucite/esphome-grove-multi-gas-v2#1]
I see in the examples on https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas/tree/master/examples/demo_background that the  method "calcVol" is called to convert the values to PPM.

When I use this component, I see values of > 400ppm for CO and NO in my home, which I don't think can be correct.  Applying calcVol gives the values of about 1-2ppm for CO and NO, which may or not be correct :)

I uploaded [this](https://github.com/derekgair/esphome-grove-multi-channel-gas-sensor-v2) to github, which is what I am currently using.

**Comment by wifwucite** [comment]
You are right, the conversion is missing. I will fix this. I found an article saying that the WHO recommends 20 ppm as upper limit and typical values would be 0.6-6 ppm.
I was actually more interested in qualitative measurements to build an [artificial nose](https://blog.benjamin-cabe.com/2021/08/03/how-i-built-a-connected-artificial-nose).

**Comment by wifwucite** [comment]
This should be fixed in the latest release.
